<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <applicationVisibilities>
        <application>Test_App_V1</application>
        <default>true</default>
        <visible>true</visible>
    </applicationVisibilities>
    <custom>true</custom>
    <loginHours>
        <mondayEnd>840</mondayEnd>
        <mondayStart>60</mondayStart>
        <tuesdayEnd>840</tuesdayEnd>
        <tuesdayStart>60</tuesdayStart>
    </loginHours>
    <loginIpRanges>
        <description>test range 1</description>
        <endAddress>10.0.0.0</endAddress>
        <startAddress>0.0.0.0</startAddress>
    </loginIpRanges>
    <loginIpRanges>
        <endAddress>255.255.255.255</endAddress>
        <startAddress>10.0.0.0</startAddress>
    </loginIpRanges>
    <recordTypeVisibilities>
        <default>true</default>
        <recordType>Case.case_rec_v1</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Case.case_rec_v2</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Case.case_rec_v3</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <userLicense>Salesforce</userLicense>
</Profile>